n1 = input('Digite um valor: ')

print(type(n1))
print('É um alfatbeto? ', n1.isalpha() )
print('É alphanumerico? ', n1.isalnum() )
print('É decimal? ', n1.isdecimal() )
print('É um digito? ', n1.isdigit() )
print('É um identifier?? ', n1.isidentifier() )
print('É lowercase?', n1.islower() )
print('É um numero?', n1.isnumeric() )
print('Poder ser imprimido?', n1.isprintable() )
print('.isspace?',n1.isspace() )
print('.istitle?',n1.istitle() )
print('É uppercase?',n1.isupper() )
print('Has spaces ', n1.isspace() )
print('{} is it a number? {}'.format(n1, n1.isalnum()) )
print('Th type of variable is', type(n1))